-- Walkwren: bookings for Kettleby Dog Walks.
-- As generated by the app builder, before the review. Kept unchanged on purpose.

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  full_name text not null,
  phone text,
  address text,
  dog_name text,
  created_at timestamptz default now()
);

create table public.walkers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  active boolean default true
);

create table public.walk_types (
  id text primary key,            -- 'solo-30', 'solo-60', 'group-60'
  label text not null,
  price_pence integer not null
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id),
  user_id uuid not null,
  walker_id uuid references public.walkers(id),
  walk_type text references public.walk_types(id),
  slot text not null,             -- '2026-10-03 9:00', as picked in the form
  price_pence integer not null,   -- sent by the booking form
  status text default 'booked',
  created_at timestamptz default now()
);

-- Customers: the form reads and writes them directly.
grant select, insert, update on public.customers to anon, authenticated;

-- Bookings: row level security on, so customers only see their own... and the owner sees everything.
alter table public.bookings enable row level security;
grant select, insert, update on public.bookings to authenticated;

create policy "customers see own bookings" on public.bookings
  for select to authenticated using (user_id = auth.uid());

create policy "admin sees all bookings" on public.bookings
  for select to authenticated using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

create policy "customers create bookings" on public.bookings
  for insert to authenticated with check (user_id = auth.uid());

create policy "customers update bookings" on public.bookings
  for update to authenticated using (true);

grant select on public.walkers, public.walk_types to anon, authenticated;
